#!/usr/bin/awk -f

BEGIN { FS = "," }

FNR == 1 {
	close(cmd)

	# strip-off path
	d = match(FILENAME, "[^/]*$")
	d = substr(substr(FILENAME, d), 1)

	# get date
	if (d !~ /^[1-9][0-9][0-9][0-9]-/)
		d = substr(d, index(d, "-") + 1, 10)
	else
		d = substr(d, 1, 10)

	cmd = sprintf("/usr/bin/sort >deaths-%s.txt", d)

	next
}

$1 {
	a = $2 + 0
	printf("%20d ", a) | cmd

	a = substr($3, 1, 3) + 0
	printf("%3d%s ", a, substr($3, 4)) | cmd

	printf("%s,%s\n", $4, $5) | cmd
}
