#!/bin/sh

# This is a best guess at matching cases cause there is no ID and later files
# have corrections like the age of the patient.

awk() {
	/usr/bin/awk "$@"
}

rm() {
	/bin/rm "$@"
}

sort() {
	/usr/bin/sort "$@"
}

tail() {
	/usr/bin/tail "$@"
}

# create report(s)
>&2 ./report "$@"

# reverse order
set -- `printf '%s\n' report-*.txt | #
awk '{ a[++i] = $0 } END { while (i) print a[i--] }'`

# most recent
p="$1"; shift

for i in "$@"; do
	printf ': %s\n' "$i" >&2
	/bin/cp -p "$i" c
	exec <"$i" && rm "$i" && ./ndiff -q - "$p" | ./super | sort >"$i"
	p="$i"
done
