#!/usr/bin/env python2.7

import sys

try:
	from html import unescape
except ImportError:
	from HTMLParser import HTMLParser
	unescape = HTMLParser().unescape

sys.stdout.write(unescape(sys.stdin.read(-1)))
sys.stdout.flush()
