#!/bin/sh

#d=-dpng
d='-dpngcairo size 820,440'

awk() {
	/usr/bin/awk "$@"
}

sed() {
	/usr/bin/sed "$@"
}

tail() {
	/usr/bin/tail "$@"
}

gp() {
	2>&1 gnuplot "$@" | tail -2 | #
	awk '!NF { next } /[Ww][Aa][Rr][Nn]/ { next }' | tail -1 >&2
}

foo() {
	shift $1;
	la="$1"
}

# set most recent input file
foo $# "$@"

foo() {
	printf '%s/%s/%s' $3 $4 $2
}

# set date
co="$IFS"
IFS=-
da=`foo $la` || exit
IFS="$co"

ab=red
be=green
#for co in 'St. Charles'; do
for co in '!Aurora,North Aurora,Elgin,South Elgin,Batavia,Geneva,St. Charles'\
  'Aurora,North Aurora' 'Elgin,South Elgin' 'Batavia,Geneva,St. Charles'; do
	for rs in 'Case Count' Death; do
		la="$co"
		echo  "$rs $la" >&2

		./totals select="$co" result="$rs" "$@" | ../../filter >tot

		case "$rs" in
		  'Case Count')
			rs=cases
			;;
		  Death)
			rs=deaths
			;;
		esac

		# gen dday & table
		../../stats tot | gp

		# gen ftot
		../../match f=dday tot | ../../step >ftot

		# percentage
		pa=`awk 'END { printf("%.1f%%", $3) }' dday`

		# daily increase
		di=`awk 'END { printf("+%d\n", $3) }' RS= ftot`

		# total
		ta=`awk 'END { print $2 }' tot`

		# doubling-time from a week ago
		ca=`sed 's/#.*//' table | #
		awk '$3 == "i" { print $2 }' | tail -7 | awk '
		NR == 1 { printf("%.1f - ", $1) }
		END { printf("%.1f", $1) }'`

		#../../label dday >labels

		/bin/rm -f a.png "$co"-"$rs".png || exit
		2>/dev/null gnuplot ../../l.gp -c ../../trends\
		  "$da $la $pa $di" "$ta $rs" "$ca"\
		  "$ab" "$be" && \
		{ /bin/mv a.png "$co"-"$rs".png || exit; }

		#exit
	done
done
