#!/bin/sh

#d=-dpng
d='-dpngcairo size 820,440'

awk() {
	/usr/bin/awk "$@"
}

foo() {
	shift $1;
	la="$1"
}

# set most recent input file
foo $# "$@"

foo() {
	printf '%s/%s/%s' $3 $4 $2
}

# set date
co="$IFS"
IFS=-
da=`foo $la` || exit
IFS="$co"

ab=red
be=green
#for co in 'St. Charles'; do
for co in '!Aurora,North Aurora,Elgin,South Elgin,Batavia,Geneva,St. Charles'\
  'Aurora,North Aurora' 'Elgin,South Elgin' 'Batavia,Geneva,St. Charles'; do
	for rs in 'Case Count' Death; do
		la="$co"
		echo  "$rs $la" >&2

		./totals select="$co" result="$rs" "$@" >totc
		case "$rs" in
		  'Case Count')
			rs=cases
			;;
		  Death)
			rs=deaths
			;;
		esac

		# last
		di=`../../filter f=tot totc` || continue

		# remove interpolated points
		awk 'NF == 3 { print $3, $2, $1 }' tot >totc

		# gen dday & table
		gnuplot -d -c ../../stats tot "$di" `awk 'NR == 1 {
		print $1; exit }' tot`

		# gen ftot
		../../match dday tot | ../../step >ftot

		# percentage
		pa=`awk 'END { printf("%.1f%%", $3) }' dday`

		# daily increase
		di=`awk 'END { printf("+%d\n", $3) }' RS= ftot`

		# total
		ta=`awk 'END { print $2 }' tot`

		# doubling-time from a week ago (damped) and now (undamped)
		ca=`awk '/^#/ { next }
		$3 == "i" {
			i = $2
			printf("%.1f - ", i)
			while (getline) {
				if ($3 != "i") exit

				i = $2
			}
		}

		END { printf("%.1f", i) }' table`

		#../../label dday >labels

		/bin/rm -f a.png "$co"-"$rs".png || exit
		gnuplot -d ../../l.gp -c ../../trends\
		  "$da $la $pa $di" "$ta $rs" "$ca"\
		  "$ab" "$be" && \
		{ /bin/mv a.png "$co"-"$rs".png || exit; }

		#exit
	done
done
