#!/usr/bin/awk -f

BEGIN {
	lineno = 1

	a = 0
	b = 1

	num[a] = 0
	num[b] = 0

	lastl[a] = ""
	lastl[b] = ""

	file[a] = "a"
	file[b] = "b"
}

function rec(i) {
	if (lastl[i] == "") {
		if (lastl[!i] != "") {
			print lastl[!i] > file[!i]
			last[!i] = ""
			num[!i] += 1
		}

		return
	}

	if (lastl[!i] == "") {
		# XXX
		if (i) {
			print lastl[i] > file[i]
			last[i] = ""
			num[i] += 1
		}

		return
	}

	if (!q) {
		print lastl[a] > file[a]
		print lastl[b] > file[b]
		lastl[a] = lastl[b] = ""
		num[a] += 1
		num[b] += 1

		return
	}

	q = 0

	if (lastl[a] ~ /^0/) lastl[b] = "0" substr(lastl[b], 2)

	print lastl[b]
}

# look for +, -+, -?+/-+?/-?+?
function plus() {
	rec(1)
}

# look for -, +, -+, -?+/-+?/-?+?
function minus() {
	rec()
}

function question() { q = 1 }

function one() {
	if      ($1 == "-") minus()
	else if ($1 == "+") plus()
	else if ($1 == "?") question()
}

/^ / {
	rec()

	next

	n = split($1, c, ",")
	for (lines = substr(c[1], 2) + 0; lineno < lines; lineno++) {
		if (getline < f == 1) {
			print
		}
	}

	if (n == 1) lines += 1
	else if (c[2] == 0) next
	else lines += c[2]

	for (; lineno < lines; lineno++) getline < f

	next
}

{ one() }

END {
	rec()

	#while (getline < f == 1) print
	exit
	close(f)

	n = 0
	while (num[a] && num[a] != n) {
		n = num[a]

		fflush("a")
		close("a")

		fflush("b")
		close("b")

		num[a] = num[b] = 0
		lastl[a] = lastl[b] = ""
		q = 0
		while ("./ndiff -q a b" | getline == 1) one()
		close("./ndiff -q a b")
		rec()
	}
}
