#!/usr/bin/awk -f

BEGIN {
	lineno = 1

	a = 0
	b = 1

	num[a] = 0
	num[b] = 0

	lastl[a] = ""
	lastl[b] = ""
}

function rec(i, f) {
	if (lastl[i] == "") return

	if (!q) {
		print lastl[i] > f
		lastl[i] = ""
		num[i] += 1

		i = !i
		if (lastl[i] == "") return

		if (f == "a") f = "b"
		else f = "a"

		print lastl[i] > f
		lastl[i] = ""
		num[i] += 1

		return
	}

	# +?-
	if (last == a) {
		print lastl[b] > "b"
		lastl[b] = ""
		num[b] += 1

		return
	}

	if (lastl[a] ~ /^0/) lastl[b] = "0" substr(lastl[b], 2)
	print lastl[b]
	lastl[a] = lastl[b] = ""
	q = 0
}

function minus() {
	rec(a, "a")
	last = a
	lastl[last] = substr($0, 3)
}

function plus() {
	rec(b, "b")
	last = b
	lastl[last] = substr($0, 3)
}

function empty() {
	rec(a, "a"); rec(b, "b")
}

function one() {
	if      ($1 == "-") minus()
	else if ($1 == "+") plus()
	else if ($1 == "?") q = 1
}

/^ / {
	empty()
	#next

	n = split($1, c, ",")
	for (lines = substr(c[1], 2) + 0; lineno < lines; lineno++) {
		if (getline < f == 1) {
			print
		}
	}

	if (n == 1) lines += 1
	else if (c[2] == 0) next
	else lines += c[2]

	for (; lineno < lines; lineno++) getline < f

	next
}

{ one() }

END {
	empty()

	while (getline < f == 1) print
	#exit
	close(f)

	n = 0
	while (num[a] != n) {
		n = num[a]

		fflush("a")
		close("a")

		fflush("b")
		close("b")

		num[a] = num[b] = 0
		lastl[a] = lastl[b] = ""
		q = 0
		while ("./ndiff -q a b" | getline == 1) one()
		close("./ndiff -q a b")

		empty()
		if (num[a] == 0) exit
		#exit
	}

	# some couldn't be matched, consider them mistakes
	#while (getline < "a" == 1) print
}
