#!/usr/bin/awk -f

BEGIN {
	FS = ","

	i = 4
	j = 1
	result = ".*"
	select = ".*"
}

NR == 1 {
	result = "^(" tolower(result) ")$"

	if (substr(select, 1, 1) == "!") {
		select = substr(select, 2)
		s = 1
	}

	gsub(/,/, "|", select)
	select = "^(" tolower(select) ")$"
}

FNR == 1 {
	if (t > 0) {
		print d, t, k
		t = 0
	}

	k++

	# strip-off path
	d = match(FILENAME, "[^/]*$")
	d = substr(substr(FILENAME, d), 1)

	# get date
	if (d !~ /^[1-9][0-9][0-9][0-9]-/)
		d = substr(d, index(d, "-") + 1, 10)
	else
		d = substr(d, 1, 10)
}

!s && tolower($i) !~ select { next }

s && tolower($i) ~ select { next }

$j ~ result { t++ }

END { if (t > 0) print d, t, k }
