#!/bin/sh

#d=-dpng
d='-dpngcairo size 820,440'

awk() {
	/usr/bin/awk "$@"
}

sed() {
	/usr/bin/sed "$@"
}

tail() {
	/usr/bin/tail "$@"
}

gp() {
	2>&1 gnuplot "$@" | tail -2 | #
	awk '!NF { next } /[Ww][Aa][Rr][Nn]/ { next }' | tail -1 >&2
}

st=$1; shift

foo() {
	shift $1;
	la="$1"
}

# set most recent input file
foo $# "$@"

foo() {
	printf '%s/%s/%s' $2 $3 $1
}

# set date
co="$IFS"
IFS=-
da=`foo $la` || exit
IFS="$co"

# split on |
foo() {
	echo $*
}
IFS='|'

for co in "$st"; do
	ab=red
	be=green

	case "$co" in
	  ..)
		co=US
		;;
	esac

	for rs in confirmed deaths active recovered; do
		la=`foo $co`
		echo  "$rs $la" >&2

		./totals select="$st" result="$rs" "$@" | ../../filter >tot

		case "$rs" in
		  confirmed)
			rs=cases
			;;
		  recovered)
		        # change sense
			ab=green
		        be=red
			;;
		esac

		# gen dday & table
		../../stats tot | gp

		# gen ftot
		../../match f=dday tot | ../../step >ftot

		# percentage
		pa=`awk 'END { printf("%.1f%%", $3) }' dday`

		# daily increase
		di=`awk 'END { printf("+%d\n", $3) }' RS= ftot`

		# total
		ta=`awk 'END { print $2 }' tot`

		# doubling-time from a week ago
		ca=`sed 's/#.*//' table | #
		awk '$3 == "i" { print $2 }' | tail -7 | awk '
		NR == 1 { printf("%.1f - ", $1) }
		END { printf("%.1f", $1) }'`

		#../../label dday >labels

		/bin/rm -f a.png "$co"-"$rs".png || exit
		2>/dev/null gnuplot ../../l.gp -c ../../trends\
		  "$da $la $pa $di" "$ta $rs" "$ca"\
		  "$ab" "$be" && \
		{ /bin/mv a.png "$co"-"$rs".png || exit; }

		#exit
	done
done
