#!/bin/sh

# run cron.sh from cron

case $# in
  1)
	;;
  *)
	echo 'Usage: cron subdir' >&2
	exit 2
	;;
esac

d=`/usr/bin/dirname "$0"`
GIT_SSH_COMMAND='ssh -i '"$d"'-id_rsa';  export GIT_SSH_COMMAND

cd "$d"'/'"$1" || exit

>cron.log 2>&1 <&- exec ./cron.sh
