#!/usr/bin/awk -f

# gen intermediate TVM values

BEGIN { f = "/dev/stdout" }

NR == 1 {
	l = $3
	t = -1
}

t == $2 { next }

{ n = $3 - l }

n > 1 {
	r = exp(log($2/t)/n); i = 1
	do {
		t *= r
		printf("%d %f\n", i + l, t) >f
	} while (++i < n)
}

{
	l = $3
	t = $2

	print $3, $2, $1 >f
}

END {
	if (l == "") exit (10)

	fflush(f)
	print l
}
