#!/bin/sh

#   http://dph.illinois.gov
# /topics-services/diseases-and-conditions/diseases-a-z-list/coronavirus

u=COVID19CountyResults
o=`/bin/date -j '+%Y %m %d %H:%M:%S-%Z'` || exit
set -- $o

o="$u"-"$1"-"$2"-"$3"-"$4".json
u=COVIDTestResults.json

u=sitefiles/$u
u=https://dph.illinois.gov/$u

curl -sqL -- "$u" | /usr/bin/tr -d \\r >"$o"
/usr/bin/awk '/"LastUpdateDate"/ { found = 1; next }
found && /}/ { printf(": "); exit }
!found { next } { printf("%s", $NF) }' "$o"
/usr/bin/file -- "$o"
