#!/bin/sh

u=+COVID19CountyResults-%Y-%m-%dT%H_%M_%SZ.txt
o=`/bin/date -ju $u` || exit

u=www2.illinois.gov/sites/coronavirus/map/Documents/COVID19CountyResults.txt
u=https://$u

curl -sqL $u | /usr/bin/tr -d \\r >$o
