#!/bin/sh

# label sparsely don't obscure previous part of line

awk() {
	/usr/bin/awk "$@"
}

paste() {
	/usr/bin/paste "$@"
}

awk 'NR == 1 { next } { print }' tot | paste "$1" - | awk 'NR == 1 {
	step = int($1/-31)
	last = $1 - 1
}

NF == 7 && ($1 - last) >= step {
	printf("%s %s %s ", $1, $3, $7)

	if ($3 > v) printf("\"\" ")

	printf("\"%.1f^{_%%}\"\n", $3)

	last = $1
}

{ v = $3 }'
