#!/bin/sh

# label sparsely don't obscure previous part of line

awk() {
	/usr/bin/awk "$@"
}

paste() {
	/usr/bin/paste "$@"
}

awk 'NR == 1 { next } { print }' tot | paste "$1" - | awk 'NR == 1 {
	step = int($1/-31) + 1
	last = $1 - 1
}

NF == 7 && (($1 - last) >= (int(log($3)/log(1000)) + step)) {
	printf("%s %s %s ", $1, $3, $7)

	if ($3 > v) printf("\"\" ")

	if ($3 >= 10) printf("\"%.1f^{_%%}\"\n", $3)
	else if ($3 >= 1) printf("\"%.2f^{_%%}\"\n", $3)
	else printf("\".%d^{_%%}\"\n", int($3*1000 + .5 ))

	last = $1
}

{ v = $3 }'
