#!/usr/bin/awk -f

BEGIN { minx = 1 }

NR == 1 {
	for (;;) {
		if ($3 > 0) {
			min = $3 + 1
			break
		}

		if (!getline) exit
	}
}

$3 <= 0 { next }

$3 < min { min = $3; minx = $1 }

$3 >= max { max = $3; maxx = $1 }

END {
	if (minx != 1) printf("%d %f %.2f%%\n", minx, min, min)

	if (maxx != minx) printf("%d %f \"\" %.2f%%\n", maxx, max, max)
}
