#!/bin/sh

awk() {
	/usr/bin/awk "$@"
}

paste() {
	/usr/bin/paste "$@"
}

sed() {
	/usr/bin/sed "$@"
}

tail() {
	/usr/bin/tail "$@"
}

tr() {

	/usr/bin/tr "$@"
}

gp() {
	2>&1 gnuplot "$@" | tail -2 | #
	awk '!NF { next } /[Ww][Aa][Rr][Nn]/ { next }' | tail -1 >&2
}

foo() {
	shift $1;
	la="$1"
}

# set most recent input file
foo $# "$@"

foo() {
	printf '%s/%s/%s' $3 $4 $2
}

# set date
co="$IFS"
IFS=-
da=`foo $la` || exit
IFS="$co"

g0=Illinois

awk '/state_testing_results/ { F = 1 } F { print }' "$la" >\%chg
/bin/rm -f ratio.png tested || exit
co=`awk '$1 ~ /"total_tested":$/ { print $2 >f; t++ }
END { print int(t/32) + 1 }' RS=, f=tested \%chg`
awk '$1 ~ /"confirmed_cases":$/ { print $2 }' RS=, \%chg >total
awk '$(NF - 1) ~ /"testDate":$/ { print $NF }' RS=, \%chg | \
  paste - total tested | >ratio awk '$3 > 0 {
	L = 100 * $2 / $3; printf("%s %s", $1, L); i++
	if (i >= n) { i = 0; printf(" %.1f", L) }
	printf("\n") }' n="$co"
co=`tail -5 ratio | awk '{ t += $2 } END { printf("%.1f", t / NR) }'`
gnuplot l.gp -c ratioplot "$da $g0"' 5 sample test-positivity rate '"$co" ||\
   exit

g1='Chicago,Cook'
g2='McHenry,Lake,Kane,DuPage,Kendall,Will,Grundy,Kankakee'
g3='Winnebago,Boone,DeKalb,Ogle'
g4='Rock Island,Whiteside,Henry'
g5='St. Clair,Madison,Monroe,Randolph,Jackson'
g6='Champaign,McLean,Tazewell,Peoria'
g7='Sangamon,Macon,Christian'
g8='Kane'
cg="!$g1","$g2","$g3","$g4","$g5","$g6","$g7","$g8","$g0"

ot=Other
ev=ot

ab=red
be=green

for co in "$cg" "$g1" "$g2" "$g3" "$g4" "$g5" "$g6" "$g7" "$g8" "$g0"; do
	eval la="\$$ev"; ev=co
	for rs in 'confirmed cases' deaths 'total tested'; do
		echo  "$rs $la" >&2

		./totals select="$co" result="$rs" "$@" | ./filter >tot

		of="`printf '%s' "$la" | tr 'A-Z' 'a-z' | tr -Cs 'a-z0-9' _`"
		case "$rs" in
		  'confirmed cases')
			rs=cases
			;;
		  'total tested')
			rs=tested
			;;
		esac
		of="$of"-"$rs".png

		# gen dday & table
		./stats tot | gp

		# gen ftot
		./match f=dday tot | ./step >ftot

		# percentage
		pa=`awk 'END { printf("%.1f%%", $3) }' dday`

		# daily increase
		di=`awk 'END { printf("+%d\n", $3) }' RS= ftot`

		# total
		ta=`awk 'END { print $2 }' tot`

		# doubling-time from a week ago
		ca=`sed 's/#.*//' table | #
		awk '$3 == "i" { print $2 }' | tail -7 | awk '
		NR == 1 { printf("%.1f - ", $1) }
		END { printf("%.1f", $1) }'`

		#../../label dday >labels

		/bin/rm -f a.png "$of" || exit
		2>/dev/null gnuplot l.gp -c trends\
		  "$da $la $pa $di" "$ta $rs" "$ca"\
		  "$ab" "$be" && \
		{ /bin/mv a.png "$of" || exit; }

		#exit

		# no tested totals per county
		case "$la"-"$rs" in
		  Illinois-deaths)
		        # change sense
			ab=green
		        be=red
			;;
		  *-deaths)
			break
			;;
		esac
	done
done
