#!/bin/sh

#d=-dpng
d=-dpngcairo

awk() {
	/usr/bin/awk "$@"
}

foo() {
	shift $1;
	echo "$1" | sed 's/[^-]*-//; s/T.*//'
}

da=`foo $# "$@"`

for co in Illinois; do
	for rs in 'confirmed cases' 'total tested' deaths; do
		./totals result="$rs" "$@" >total
		./plot -gst "$co $rs $da" $d -o "$co"-"$rs"-tot.png total

		<total ./cum | awk 'NF==2{print NR-1,$2}' | tail>\%chg
		./plot -gst "$co $rs $da" $d -o "$co"-"$rs"-chg.png \%chg

		<total ./log | awk 'NF==2{print NR-1,$2}'>lg10
		./plot -gst "$co $rs $da" $d -o "$co"-"$rs"-log.png lg10
	done
done
