#!/usr/bin/awk -f
function o(i, j, k) {
	printf(f, i, j, k, j, j)
}

END {
	f = "set xrange [%d:%d]; stats '%s' u 3:(log($2)) noout\n" \
	  "r = exp(STATS_slope); P = exp(STATS_intercept)\n" \
	  "fit f(x) 'totc' u 3:2 via r, P\n" \
	  "print %d, r, d/log(r), P*r**%d, P\n"

	if ($3 > 7) k = 7
	else k = $3

	j = 3
	if (j > k) exit

	print "d = log(2); set print 'dday'; f(x) = P*r**x"
	print "set fit quiet; set fit logfile '/dev/null'"

	i = 1
	o(i, j++, "totc")

	while (j < k)

	while (j < $3) o(i++, j++)
}
