#!/usr/bin/awk -f
BEGIN {
	RS = ","

	select = "Illinois"
	result = "confirmed cases"
}

NR == 1 {
	select = "\"" tolower(select) "\""

	# prevent gnuplot from using subscripts in enhanced title
	sub(/ /, "_", result)
	result = "\"" result "\":"
}

NF > 2 && $(NF - 1) ~ /"County":$/ && tolower($NF) == select {
	if (found) exit 1
	found = 1
}

found && $1 == result { print $2; found = 0; nextfile }
