#!/bin/sh

awk() {
	/usr/bin/awk "$@"
}

sort() {
	/usr/bin/sort "$@"
}

tail() {
	/usr/bin/tail "$@"
}

st=$1; shift

foo() {
	shift $1;
	la="$1"
}

# set most recent input file
foo $# "$@"

foo() {
	printf '%s/%s/%s' $2 $3 $1
}

# set date
co="$IFS"
IFS=-
da=`foo $la` || exit
IFS="$co"

# split on |
foo() {
	echo $*
}
IFS='|'

tc=totc

for co in "$st"; do
	ab=red
	be=green

	case "$co" in
	  ..)
		co=US
		biny() { ./biny "$@" >x2tics.txt; }
		;;
	  *)
		/bin/rm -f x2tics.txt || exit
		touch x2tics.txt || exit
		biny() { :; }
		;;
	esac

	#for rs in positive; do
	for rs in positive death hospitalized inIcuCumulative\
	  onVentilatorCumulative recovered totalTestResults; do
		la=`foo $co`
		echo  "$rs $la" >&2

		./totals select="$st" result="$rs" "$@" >"$tc"
		biny select="$st" result="$rs" "$@"

		of="$co"-
		case "$rs" in
		  positive)
			rs=cases
			of="$of"2c
			;;
		  death)
			rs=deaths
			of="$of"2d
			;;
		  totalTestResults)
			rs=tested
			of="$of"5t
			;;
		  hospitalized)
			rs=hospitalized
			of="$of"8h
			;;
		  recovered)
			rs=recovered
			of="$of"8r

		        # change sense
			ab=green
		        be=red
			;;
		  inIcuCumulative)
			rs='in ICU'
			of="$of"8xi
			;;
		  onVentilatorCumulative)
			rs=vented
			of="$of"8xv
			;;
		esac

		# last
		di=`../../filter f=tot "$tc"` || continue

		# remove interpolated points
		awk 'NF == 3 { print $3, $2, $1 }' tot >"$tc"

		awk '{ print $3 - n, $2 - t, $1; t = $2 }' n="$di" "$tc" >daily
		tc=toti

		# gen dday & table
		gnuplot -d -c ../../stats tot "$di" `awk 'NR == 1 {
		print $1; exit }' tot`

		# gen ftot
		../../match dday tot | ../../step >ftot

		# percentage
		pa=`awk 'END { printf("%.1f%%", $3) }' dday`

		# daily increase
		di=`awk 'END { printf("+%d\n", $3) }' RS= ftot`

		# total
		ta=`awk 'END { print $2 }' tot`

		# doubling-time from a week ago (damped) and now (undamped)
		ca=`awk '/^#/ { next }
		$3 == "i" {
			i = $2
			printf("%.1f - ", i)
			while (getline) {
				if ($3 != "i") exit

				i = $2
			}
		}

		END { printf("%.1f", i) }' table`

		../../label dday >labels

		/bin/rm -f a.png b.png "$of".png "$of"_g.png || exit
		gnuplot -d ../../l.gp -c ../../trends\
		  "$da $la $pa $di" "$ta $rs" "$ca" "$ab" "$be" &&\
		{ /bin/mv a.png "$of".png || exit; }
		awk -F+ '$2 != "0-0" { print } END { print t }'\
		  t="$da $la $pa $di" x2tics.txt >"$of".png.txt || exit
		../../groovy "$rs $co $da" || exit
		/bin/mv b.png "$of"_g.png || exit

		#exit
	done
done

/bin/rm -f x2tics.txt || exit

/bin/rm -f tot ratio.png "$co"-5r.png || exit
awk '{
	printf("\"%s/%s/%s\" %s",
	  substr($1, 6, 2), substr($1, 9, 2), substr($1, 1, 4), $2); i++
	if (i >= n) { i = 0; printf(" %.1f", $2) }
	printf("\n")
}' n=`awk '{ print $0, "t" }' toti | sort -mnk3 totc - | awk 'd != $1 && t > 0 {
	print d, c * 100 / t >"tot"
	d = $1; n++
} 

NF == 4 { t = $2 }

NF == 3 { c = $2 }

END { print int(n/32) + 1 }'` tot >ratio
ti=`tail -5 ratio | awk '{ t += $2 } END { printf("%.1f", t / NR) }'`
gnuplot ../../l.gp -c ../../ratioplot\
  "$da $co"' 5 sample test-positivity rate '"$ti" || exit
/bin/mv ratio.png "$co"-5r.png || exit
printf '%s' "$da $co"' 5 sample test-positivity rate '"$ti" >"$co"-5r.png.txt
