#!/bin/sh

#d=-dpng
d='-dpngcairo size 820,440'

awk() {
	/usr/bin/awk "$@"
}

sed() {
	/usr/bin/sed "$@"
}

sort() {
	/usr/bin/sort "$@"
}

tail() {
	/usr/bin/tail "$@"
}

gp() {
	2>&1 gnuplot "$@" | tail -2 | #
	awk '!NF { next } /[Ww][Aa][Rr][Nn]/ { next }' | tail -1 >&2
}

st=$1; shift

foo() {
	shift $1;
	la="$1"
}

# set most recent input file
foo $# "$@"

foo() {
	printf '%s/%s/%s' $2 $3 $1
}

# set date
co="$IFS"
IFS=-
da=`foo $la` || exit
IFS="$co"

# split on |
foo() {
	echo $*
}
IFS='|'

tc=totc

for co in "$st"; do
	ab=red
	be=green

	case "$co" in
	  ..)
		co=US
		biny() { ./biny "$@" >x2tics.txt; }
		;;
	  *)
		/bin/rm -f x2tics.txt || exit
		touch x2tics.txt || exit
		biny() { :; }
		;;
	esac

	for rs in positive death hospitalized inIcuCumulative\
	  onVentilatorCumulative recovered totalTestResults; do
		la=`foo $co`
		echo  "$rs $la" >&2

		./totals select="$st" result="$rs" "$@" >"$tc"
		../../filter "$tc" >tot
		tc=toti

		biny select="$st" result="$rs" "$@"

		of="$co"-
		case "$rs" in
		  positive)
			rs=cases
			of="$of"2c
			;;
		  death)
			rs=deaths
			of="$of"2d
			;;
		  totalTestResults)
			rs=tested
			of="$of"5t
			;;
		  hospitalized)
			rs=hospitalized
			of="$of"8h
			;;
		  recovered)
			rs=recovered
			of="$of"8r

		        # change sense
			ab=green
		        be=red
			;;
		  inIcuCumulative)
			rs='in ICU'
			of="$of"8xi
			;;
		  onVentilatorCumulative)
			rs=vented
			of="$of"8xv
			;;
		esac

		# gen dday & table
		../../stats tot | gp

		# gen ftot
		../../match f=dday tot | ../../step >ftot

		# percentage
		pa=`awk 'END { printf("%.1f%%", $3) }' dday`

		# daily increase
		di=`awk 'END { printf("+%d\n", $3) }' RS= ftot`

		# total
		ta=`awk 'END { print $2 }' tot`

		# doubling-time from a week ago
		ca=`sed 's/#.*//' table | #
		awk '$3 == "i" { print $2 }' | tail -7 | awk '
		NR == 1 { printf("%.1f - ", $1) }
		END { printf("%.1f", $1) }'`

		#../../label dday >labels

		of="$of".png
		/bin/rm -f a.png "$of" || exit
		2>/dev/null gnuplot ../../l.gp -c ../../trends\
		  "$da $la $pa $di" "$ta $rs" "$ca" "$ab" "$be" &&\
		{ /bin/mv a.png "$of" || exit; }
		awk -F+ '$2 != "0-0" { print } END { print t }'\
		  t="$da $la $pa $di" x2tics.txt >"$of".txt || exit

		#exit
	done
done

/bin/rm -f x2tics.txt || exit

/bin/rm -f tot ratio.png "$co"-5r.png || exit
awk '{
	printf("\"%s/%s/%s\" %s",
	  substr($1, 6, 2), substr($1, 9, 2), substr($1, 1, 4), $2); i++
	if (i >= n) { i = 0; printf(" %.1f", $2) }
	printf("\n")
}' n=`awk '{ print $0, "t" }' toti | sort -mnk3 totc - | awk 'd != $1 && t > 0 {
	print d, c * 100 / t >"tot"
	d = $1; n++
} 

NF == 4 { t = $2 }

NF == 3 { c = $2 }

END { print int(n/32) + 1 }'` tot >ratio
ti=`tail -5 ratio | awk '{ t += $2 } END { printf("%.1f", t / NR) }'`
gnuplot ../../l.gp -c ../../ratioplot\
  "$da $co"' 5 sample test-positivity rate '"$ti" || exit
/bin/mv ratio.png "$co"-5r.png || exit
printf '%s' "$da $co"' 5 sample test-positivity rate '"$ti" >"$co"-5r.png.txt
