#!/usr/bin/awk -f

# print value with key k

BEGIN { FS = ":"; RS = ","; k="data" }

NR == 1 { k = sprintf("%s", k) }

# awk seems to escape fmtstr
tolower($1) ~ k {
	for (i = 2; i < NF; i++) printf("%s:", $i)
	printf("%s", $i)
	exit
}
