#!/bin/sh

o=`/bin/date -j '+%Y-%m-%d-%H:%M:%S-%Z'` || exit
u=https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2

curl -sqL -- "$u" | /usr/bin/tr -d \\r >"$o".html || exit
./json "$o".html >"$o".json || exit
./csv "$o".json || exit

/usr/bin/awk -F, '{ printf("%s: ", $NF); exit }' "$o".csv
/usr/bin/file -- "$o".json "$o".csv
[ -t 0 ] && echo add "$o".json || git add -v "$o".json

# https://en.wikipedia.org/wiki/Template:2019%E2%80%9320_
# coronavirus_pandemic_data/Poland_medical_cases

# https://en.wikipedia.org/wiki/User:Natanieluz

# https://twitter.com/micalrg/status/1238508622591725568

# https://docs.google.com/spreadsheets/d/
# 1ierEhD6gcq51HAm433knjnVwey4ZE5DCnu1bW7PRG3E/htmlview?usp=sharing#

# Tariqabjotu broke it, but all three templates at once still worked:
# https://en.wikipedia.org/w/index.php?title=User_talk:Tariqabjotu&action=edit&section=34
# curprev 16:40, 4 May 2020 Tariqabjotu talk contribs m 76,746 bytes -13
# top: updating to "COVID-19" following moves undo Tag: AWB
# curprev 12:33, 4 May 2020 Tariqabjotu talk contribs m  76,690 bytes 0
# Tariqabjotu moved page Template:2019–20 coronavirus pandemic data/Poland medical cases to Template:COVID-19 pandemic data/Poland medical cases: consistency with move at COVID-19 pandemic undo

# wikipedia seems to have moved Poland to the less informative plots provided
# for other countries, use Michał Rogalski's google sheet instead now:
# micalrg@gmail.com www.micalrg.pl facebook.com/micalrg.graf twitter.com/micalrg
# http://bit.ly/covid19-poland
# https://docs.google.com/spreadsheets/d/
#  1ierEhD6gcq51HAm433knjnVwey4ZE5DCnu1bW7PRG3E/

# how to get CSV
# https://docs.google.com/spreadsheets/d/DOCUMENT_ID/export?exportFormat=csv
# https://webapps.stackexchange.com/a/91671
# https://stackoverflow.com/a/48658861
# https://stackoverflow.com/questions/33713084/
#  download-link-for-google-spreadsheets-csv-export-with-multiple-sheets#
#  comment59613928_33727897

u='gviz/tq?tqx=out:csv&sheet=Testy'
u='1ierEhD6gcq51HAm433knjnVwey4ZE5DCnu1bW7PRG3E/'"$u"
u='https://docs.google.com/spreadsheets/d/'"$u"
curl -fSsqLo sheet -- "$u" && ../kane/conv sheet >sheet.csv

# might as well still try and get the latest from wikimedia

# https://en.wikipedia.org/wiki/Statistics_of_the_COVID-19_pandemic_in_Poland

u='&intestactions=edit&intestactionsdetail=full'
u='&titles=Template%3ACOVID-19%20pandemic%20data%2FPoland%20medical%20cases'"$u"
#u='Poland%20medical%20cases&intestactions=edit&intestactionsdetail=full'
#u='&titles=Template%3A2019%E2%80%9320%20coronavirus%20pandemic%20data%2F'"$u"
u=\
'&format=json&formatversion=2&prop=revisions%7Cinfo&rvprop=content%7Ctimestamp'\
"$u"
u='https://en.m.wikipedia.org/w/api.php?action=query'"$u"

curl -sqL -- "$u" |\
  ../json '["query"]["pages"][0]["revisions"][0]["content"]' |\
  /usr/bin/sed 's/^|-$//' >wiki.sgml || exit
printf '%s\n\n' 20*-???.csv | ./wiki wiki.sgml >wiki.csv || exit
