#!/bin/sh

o=`/bin/date -j '+%Y-%m-%d-%H:%M:%S-%Z'` || exit
u=https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2

curl -sqL -- "$u" | /usr/bin/tr -d \\r >"$o".html || exit
./json "$o".html >"$o".json || exit
./csv "$o".json || exit

/usr/bin/awk -F, '{ printf("%s: add ", $NF); exit }' "$o".csv
/usr/bin/file -- "$o".json "$o".csv

errexit() {
	echo "failed to create wiki.csv with status: $1" >&2
	exit $1
}

u='Poland%20medical%20cases&intestactions=edit&intestactionsdetail=full'
u='&titles=Template%3A2019%E2%80%9320%20coronavirus%20pandemic%20data%2F'"$u"
u=\
'&format=json&formatversion=2&prop=revisions%7Cinfo&rvprop=content%7Ctimestamp'\
"$u"
u='https://en.m.wikipedia.org/w/api.php?action=query'"$u"

curl -sqL -- "$u" |\
  ../json '["query"]["pages"][0]["revisions"][0]["content"]' |\
  /usr/bin/sed 's/^|-$//' | ./wiki >tot || errxit $?
/bin/mv tot wiki.csv
