#!/bin/sh

#d=-dpng
d='-dpngcairo size 820,440'

awk() {
	/usr/bin/awk "$@"
}

tail() {
	/usr/bin/tail "$@"
}

foo() {
	shift $1;
	la="$1"
}

# set most recent input file
foo $# "$@"

foo() {
	printf '%s.%s.%s' $3 $2 $1
}

# set date
co="$IFS"
IFS=-
da=`foo $la` || exit
IFS="$co"

# split on |
foo() {
	echo $*
}
IFS='|'

ab=red
be=green

la='|lubuskie|małopolskie|podkarpackie'
for co in 'mazowieckie|podlaskie|lubelskie|świętokrzyskie' \
  'pomorskie|zachodniopomorskie|kujawsko-pomorskie|warmińsko-mazurskiei' \
  'łódzkie|wielkopolskie|dolnośląskie|opolskie|śląskie'"$la" 'Cała Polska' ; do
	tc=totc
	for rs in 'liczba' 'liczba zgonów' 'badań'; do
		case "$co"-"$rs" in
		  *Polska-bad*)
			ab=green
			be=red
			;;
		  *-bad*)
			continue
			;;
		esac

		la=`foo $co`
		echo  "$rs $la" >&2

		case "$rs" in
		  bad*)
			./totalw wiki.csv >"$tc"
			../../filter "$tc" >tot
			;;
		  *)
			./totals select="$co" result="$rs" "$@" >"$tc"
			../../filter "$tc" >tot
			;;
		esac

		# last
		di=`../../filter f=tot "$tc"` || continue

		# remove interpolated points
		awk 'NF == 3 { print $3, $2, $1 }' tot >"$tc"

		awk '{ print $3 - n, $2 - t, $1; t = $2 }' n="$di" "$tc" >daily
		tc=toti

		# gen dday & table
		gnuplot -d -c ../../stats tot "$di" `awk 'NR == 1 {
		print $1; exit }' tot`

		# gen ftot
		../../match dday tot | ../../step >ftot

		# percentage
		pa=`awk 'END { printf("%.1f%%", $3) }' dday`

		# daily increase
		di=`awk 'END { printf("+%d\n", $3) }' RS= ftot`

		# total
		ta=`awk 'END { print $2 }' tot`

		# doubling-time from a week ago (damped) and now (undamped)
		ca=`awk '/^#/ { next }
		$3 == "i" {
			i = $2
			printf("%.1f - ", i)
			while (getline) {
				if ($3 != "i") exit

				i = $2
			}
		}

		END { printf("%.1f", i) }' table`

		../../label dday >labels

		ta="$ta ="
		/bin/rm -f a.png "$co"-"$rs".png || exit
		gnuplot -d l.gp -c ../../trends\
		  "$da $la $pa $di" "$ta $rs" "$ca"\
		  "$ab" "$be" && \
		{ /bin/mv a.png "$co"-"$rs".png || exit; }

		#exit
	done

	#exit
done

/bin/mv 'Cała Polska-badań.png' tested.png || exit

awk '{ print $0, "t"}' toti | sort -m totc - | awk '
d != $1 && t > 0 && c > 0 {
	print d, c * 100 / t, n
	n++
} 

{ d = $1 }

NF == 4 { t = $2 }

NF == 3 { c = $2; n = $3 }

END {
	print $1, c * 100 / t, n
}' | awk '{
	printf("\"%s/%s/%s\" %s %s\n",
	  substr($1, 6, 2), substr($1, 9, 2), substr($1, 1, 4), $2, $3) }' >tott
awk '{
	printf("%s %s", $1, $2); i++
	if (i >= n) { i = 0; printf(" %.1f", $2) }
	printf("\n")
}' n=`awk 'NR == 1 { i = $3 } END { print int(($3 - i)/32) + 1 }' tott`\
  tott >ratio
ti=`tail -5 ratio | awk '{ t += $2 } END { printf("%.1f", t / NR) }'`
gnuplot l.gp -c ../../ratioplot\
  "$da $co"' liczba/badań '"$ti"'% 5 prób' || exit
