#!/bin/sh

#http://dph.illinois.gov/sites/default/files/COVID19/il_illinois_zip_codes.json
#http://dph.illinois.gov/sites/default/files/Illinois_County_Geo_ch.json

o=`/bin/date -j '+%Y %m %d %H:%M:%S-%Z'` || exit
set -- $o
o=-"$1"-"$2"-"$3"-"$4".json

n=''
foo() {
	f=$1$o; shift
	n="$n $f"
	u="$*"
}

u='http://dph.illinois.gov/sitefiles/COVIDHistoricalTestResults.json?nocache=1'
for u in \
  zip\ http://dph.illinois.gov/sitefiles/COVIDZip.json?nocache=1 \
  demo\ http://dph.illinois.gov/sitefiles/CountyDemos.json?nocache=1 \
  tests\ $u; do
	foo $u
	curl -sqL -- "$u" | /usr/bin/tr -d \\r >"$f"
done

/usr/bin/file -- $n
echo "add *$o"
